---

- name: Connect to the server
  command: "{{keycloak_home}}/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin"

- name: Create a default client
  command: "{{keycloak_home}}/bin/kcadm.sh create clients -r master -s clientId=test -s enabled=true"
  ignore_errors: yes

- name: Create or update Keycloak client
  keycloak_client:
    auth_client_id: admin-cli
    auth_keycloak_url: http://localhost:8080/auth
    auth_realm: master
    auth_username: admin
    auth_password: admin
    client_id: test
    state: present
    enabled: True
    redirect_uris:
      - http://localhost:8000/callback/*

- name: Create a user to test with
  command: "{{keycloak_home}}/bin/kcadm.sh create users -r master -s username=testuser -s enabled=true -s email=test@mail.com -s firstName=First -s lastName=Last"
  ignore_errors: yes

- name: Set/Reset user password
  command: "{{keycloak_home}}/bin/kcadm.sh set-password -r master --username testuser --new-password pass -t=false"
